### PR TITLE
Project Euler Problem 1

### PR DESCRIPTION
**Pull request by maaquib**
Project Euler Problem 1 Solution

### CODE REVIEW

**Comment by jarrodtaylor** [comment]
Nice job not brute forcing it. The usual approach I see is:

```ruby
total = 0
(1..999).each { |i| total += i if (i % 3 == 0) || (i % 5 == 0) }
```

It looks like you're adding the sum of number divisible by 5 to the sum of numbers divisible by 3, then subtracting the sum of numbers divisible by 15 to balance out the duplicates.

Here's what needs to be changed to get this into shape.

- [ ] TomDoc it, even the private method. What are the parameters, what kind of data type should they be, what are they used for? What's the return type? Give an IRB style example of generic use. One of the downsides of Ruby is that it's not very explicit. What if I passed in a "1" as a string instead? No need to account for bad data types, just comment what's expected.
- [ ] ```(1000-1)``` is duplicated a lot. Move it to a class or instance var. Use those liberally in Ruby, everyone else does, and it makes the class easy to configure. That will also allow you to remove the ```num``` param from the ```sum()``` method. Sometimes I'd argue to make it a param on the ```solution()``` method, but in this case we're always looking for 999. If we get to a later problem where this becomes reusable, we can refactor.
- [ ] Ruby already has a ```sum()``` method, so a different, more descriptive name would be better. That method is really returning the sum of number divisible by another number, so "sum" doesn't fit.

@richardrissanen @rishabhsaha Anything I'm missing?

**Comment by jarrodtaylor** [comment]
Another quick note on TomDoc'ing: It's really about taking a clever solution and making it clear to people who haven't seen it before. If I didn't understand the math on this one, a method named ```sum``` that was doing division would be very confusing. You've both probably already seen a lot of code in the CFG app that wasn't clear. It all probably made sense at the time to whoever wrote it.

**Comment by maaquib** [comment]
@jarrodtaylor I incorporated your suggestions. Added tomdoc, instance variable and an explanation of the mathematical approach. Let me know if it looks fine now.

**Comment by jarrodtaylor** [comment]
:+1: 

Much better.

I rearranged the comments a bit. Since ```private``` marks every method below it as private, it doesn't need to be in between the comment and the method. I also added data types to the return comments.

Look over it, do a rebase to [squash the commits into one](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html), then go ahead and merge.

Also, take a look at the branch for problem 2. See if you can help clean it up.

**Pull request merged**
